linters:
  eslint:
    config: 'client/.eslintrc.json'
  rubocop:
    display_cop_names: true
    config: './rubocop.yml'

files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "*/rails_helper.rb"
    - "spec/*"
